
kind: Service
apiVersion: v1
metadata:
  name: detail-service
  labels:
    app: detail-service
    visualize: "true"
spec:
  ports:
    - port: 80
      targetPort: 8080
      name: http
  selector:
    app: detail-service
    serving: "true"
 