
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service-v1
  labels:
    app: product-service
    version: "1.0"
    visualize: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
      version: "1.0"
      serving: "true"
  template:
    metadata:
      labels:
        app: product-service
        serving: "true"
        version: "1.0"
        visualize: "true"
    spec:
      containers:
      - name: product-service
        image: gcr.io/project-vnv/product:latest
        livenessProbe:
          initialDelaySeconds: 90
          httpGet:
            path: /actuator/health
            port: 8080
        readinessProbe:
          httpGet:
            path: /
            port: 8080
        ports:
        - containerPort: 8080
          name: http
