
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rettings-service
  labels:
    app: rettings-service
    version: "1.0"
    visualize: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rettings-service
      version: "1.0"
      serving: "true"
  template:
    metadata:
      labels:
        app: rettings-service
        serving: "true"
        version: "1.0"
        visualize: "true"
    spec:
      containers:
      - name: rettings-service
        image: gcr.io/project-vnv/rettings:v1
        ports:
        - containerPort: 8080
          name: http
